config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  root to: "variouses#top"

  # アバウトページ
  get "variouses/about"       => "variouses#about"

  # ユーザーアクション
  get "users/:id/videos"      => "users#videos", as: "users_videos"
  get "users/withdraw"        => "users#withdraw"
  get "users/:id/favorites" => "users#favorites", as: "users_favorites"

  # 検索機能
  get "search" => "videos#search"

  # 新規会員登録の時のルーティングエラーを修正
  get '/users', to: redirect("/users/sign_up")

  resources :users,           only: [:show, :edit, :update, :destroy] do
    resource :relationships,  only: [:create, :destroy]
    get :follows,   on: :member
    get :followers, on: :member
    # memberはidを取得できるようにする
  end

  # 動画アクション
  resources :videos do
    resource  :likes,      only: [:create, :destroy]
    resource  :favorites,  only: [:create, :destroy]
    resources :comments,   only: [:create, :destroy]
  end

  # ルーム機能
  resources :rooms do
    resources   :room_messages, only: [:create, :destroy]
    resources   :room_videos,   only: [:create, :destroy]
    resource    :room_user,     only: [:create, :destroy]
  end

  resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :videos,             dependent: :destroy
  has_many :comments,           dependent: :destroy
  has_many :favorites,          dependent: :destroy
  has_many :likes,              dependent: :destroy
  has_many :room_messages,      dependent: :destroy
  has_many :room_videos,        dependent: :destroy
  has_many :room_users,         dependent: :destroy

  has_many :room, through: :room_users

  # ユーザーのお気に入りした動画を取得する
  # 下記はfavoritesを通してvideoから情報を集めている
  has_many :favorites_videos, dependent: :destroy, through: :favorites, source: :video

  # フォロー・フォロワーの情報を集める
  # has_many :relatinshipだと２通り書かなくてはならず名前被りが起こるので中間テーブル名を再定義する

  # ============ 自分がフォローしているユーザーとの関連 ===============
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # ============================================================

  # ============ 自分がフォローされるユーザーとの関連 ===============
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  # ===========================================================

  # 通知機能用の記述
  # 自分からの通知
  has_many  :active_notifications,  class_name: 'Notification',  foreign_key: 'visitor_id',  dependent: :destroy
  # 相手からの通知
  has_many  :passive_notifications, class_name: 'Notification',  foreign_key: 'visited_id',  dependent: :destroy

  # Userがfollow済みかどうか判定
  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  # ActiveStorage画像リサイズメソッド
  def thumbnail
    profile_image.variant(resize: '150x150').processed
  end

  # フォローされた時に通知がされるメソッド
  def create_notification_follow!(current_user)
    # 同じ通知レコードが存在しない時だけ、レコードを作成
    temp = Notification.where(["visitor_id = ? and Visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout "devise"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @current_user = current_user
    @user = User.find(params[:id])
    @videos = @user.videos.order(id: "DESC").limit(4)
    @favo_videos = @user.favorites_videos.order(id: "DESC").limit(4)
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    case !params[:user][:name].blank?
      when true
        unless params[:user][:profile_image].nil?
          if !params[:user][:profile_image].content_type.in?(%('profile_image/jpeg profile_image/png'))
            flash.now[:error]="・jpegまたはpngファイルを添付してください"
            render :edit
          else
            @user.update(user_params)
            redirect_to user_path(@user)
          end
        else
          @user.update(user_params)
          redirect_to user_path(@user)
        end
      else
        flash.now[:error]="・ユーザーネームを入力して下さい"
        render :edit
      end
  end

  def favorites
    @user = User.find(params[:id])
    @current_user = current_user
    @favorites = @user.favorites_videos.page(params[:page]).per(5).includes(user: :videos)
  end

  def videos
    @current_user = current_user
    @user = User.find(params[:id])
    @user_videos = @user.videos.page(params[:page]).per(5).includes(:user)
  end

  def follows
    @current_user = current_user
    @user = User.find(params[:id])
    @users = @user.followings.where(release_status: 1).page(params[:page]).per(6)
  end

  def followers
    @current_user = current_user
    @user = User.find(params[:id])
    @users = @user.followers.where(release_status: 1).page(params[:page]).per(6)
  end

  def withdraw
    @user = current_user
  end

  def destroy
    @user = current_user
    @user.destroy
    redirect_to root_path
  end

  private

  # ログイン中ユーザー以外のユーザー情報を直接編集できないようにする
  def ensure_correct_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_back(fallback_location: user_path(current_user))
    end
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :release_status, :deleted_status)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_attachment.html.erb
<% if user.profile_image.attached? %>
  <%= image_tag(user.thumbnail) %>
<% else %>
  <%= image_tag "/no-img-human.png",size: '150x150' %>
<% end %>

app/views/users/_follow.html.erb
<% unless user == current_user %>
  <div class="row">
    <% if user.followed_by?(current_user) %>
      <p><%= link_to "フォロー中！", user_relationships_path(user), method: :delete, remote: true %></p>
    <% else %>
      <p><%= link_to "フォローする！", user_relationships_path(user) , method: :post, remote: true %></p>
    <% end %>
  </div>
<% end %>

app/views/users/_unless_user.html.erb
<div class="container">
  <div class="row">
    <div class="user-profile">
      <%= render partial: "users/attachment", locals: { user: @user} %>
      <p><%= @user.name %></p>
    </div>
    <div class="user-follower">
      <div class="follow">
        <p>フォロー (<%= @user.followings.count %>)</p>
      </div>
      <div class="follower">
        <p>フォロワー (<%= @user.followers.count %>)</p>
      </div>
    </div>
  </div>
  <div class="unless-acaunt row">
    <p>【このアカウントは現在非公開となっています】</p>
  </div>
</div>

app/views/users/_user_details.html.erb
<div id="user-detalis">
  <div id="details">
    <%= link_to user_path(user), class: "user-info" do %>
    <div class="user-image">
      <%= render partial: "users/attachment", locals: { user: user} %>
    </div>
    <div class="user-name">
      <%= user.name %>
    </div>
    <% end %>

    <div class="link notification">
      <%= link_to notifications_path do %>
        <% if unchecked_notifications.blank? %>
          <%= icon('fas', 'bell') %>
        <% else %>
          <span class="fa-stack">
            <%= icon('fas', 'bell') %>
            <%= icon('fas', 'circle') %>
          </span>
        <% end %>
      <% end %>
      <p class="fukidashi">通知</p>
    </div>
    <div class="link new-video">
      <%= link_to new_video_path do %>
        <%= icon('fas', 'video') %>
      <% end %>
      <p class="fukidashi">動画を投稿</p>
    </div>
    <div class="link user-post-videos">
      <%= link_to users_videos_path(user) do %>
        <%= icon('fas', 'film') %>
      <% end %>
      <p class="fukidashi">投稿した動画</p>
    </div>
    <div class="link user-fovorite-videos">
      <%= link_to users_favorites_path(user) do %>
        <%= icon('far', 'file-video') %>
      <% end %>
      <p class="fukidashi">お気に入り動画</p>
    </div>
    <div class="link user-follows">
      <%= link_to follows_user_path(user) do %>
        <%= icon('fas', 'user-plus') %>
      <% end %>
      <p class="fukidashi">フォロー</p>
    </div>
    <div class="link user-followers">
      <%= link_to followers_user_path(user) do %>
        <%= icon('fas', 'users') %>
      <% end %>
      <p class="fukidashi">フォロワー</p>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div id="edit" class="container">

  <%= form_with model: @user,　method: :patch, local: true do |f| %>

    <div class="edit_form">
      <div class="error">
        <strong><%= flash[:error] %></strong>
      </div>
      <div class="field　user-name">
        <p>ユーザーネーム</p>
        <%= f.text_field :name %>
      </div>

      <div class="field user-image">
        <p>プロフィールイメージ</p>
        <%= f.file_field :profile_image %>
      </div>

      <div class="field user-introduction">
        <p>ユーザー紹介</p>
        <%= f.text_area :introduction %>
      </div>

      <div class="field user-release_status">
        <h5>公開ステータス</h5>
        <p class="status_menu">※非公開にすると、ユーザーの情報や動画は他のユーザーからは見えないようになります</p>
        <div class="radio_button">
          <label><%= f.radio_button :release_status, 1 %> 公開</label>
          <label><%= f.radio_button :release_status, 0 %> 非公開</label>
        </div>
      </div>

      <div class="actions form-btn">
        <%= f.submit "更新", class: "btn btn-success" %>
      </div>

      <div class="user-delete">
        <%= link_to "キャンセル", user_path(@user), class: "btn btn-secondary" %>
        <%= link_to users_withdraw_path, class: "withdraw btn btn-danger" do %>
          <p>アカウント削除</p>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/favorites.html.erb
<div id="videos">
  <%= render partial: 'users/user_details', locals: { user: @current_user }  %>

<div class="container">
  <div class="row">

    <div class="col-lg-12">
      <h2>お気に入り動画一覧</h2>

      <div id="favorited" class="jscroll">
        <%= render partial: 'videos/user_favorite_videos', locals: { favorites: @favorites } %>
        <%= paginate @favorites %>
      </div>

    </div>
  </div>
</div>
</div>

app/views/users/followers.html.erb
<div id="follow-wrap">
  <%= render partial: 'users/user_details', locals: { user: @current_user} %>

  <div class="container">
    <div class="row">
      <h2>フォロワー</h2>
    </div>
    <div class="jscroll">
      <% @users.each do |user| %>
        <div class="row">
          <div class="col-lg-3 col-md-3 col-sm-5">
            <%= link_to user_path(user) do %>
            <%= render partial: "users/attachment", locals: { user: user}, class: "attachment_image" %>
            <p><%= user.name %></p>
            <% end %>
          </div>
          <div class="col-lg-8 col-md-8 col-sm-7">
            <p class="introduction"><%= user.introduction %></p>
          </div>
        </div>
      <% end %>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/follows.html.erb
<div id="follow-wrap">
  <%= render partial: 'users/user_details', locals: { user: @current_user} %>

  <div class="container">
    <div class="row">
      <h2>フォローユーザー</h2>
    </div>
    <div class="jscroll">
      <% @users.each do |user| %>
      <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-5">
          <%= link_to user_path(user) do %>
          <%= render partial: "users/attachment", locals: { user: user} %>
          <p><%= user.name %></p>
          <% end %>
        </div>
        <div class="col-lg-8 col-md-8 col-sm-7">
          <p class="introduction"><%= user.introduction %></p>
        </div>
      </div>
      <% end %>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div id="show">

  <% if @user.release_status == 0 && @user != current_user %>

    <%= render partial: 'users/unless_user', locals: { user: @user} %>

  <% else %>

  <div class="container">

    <div class="row">
      <div class="user-profile">
        <%= render partial: "users/attachment", locals: { user: @user} %>
        <p><%= @user.name %></p>
      </div>
      <div class="user-follower">
        <div class="follow">
          <%= link_to follows_user_path(@user) do %>
          <p>フォロー (<%= @user.followings.count %>)</p>
          <% end %>
        </div>
        <div class="follower">
          <%= link_to followers_user_path(@user) do %>
          <p>フォロワー (<%= @user.followers.count %>)</p>
          <% end %>
        </div>
      </div>
    </div>

    <!-- フォロー機能 -->
    <div id="follow" class="user-follow">
      <%= render partial: 'users/follow', locals: { user: @user} %>
    </div>

    <div class="current-user-contents row">
      <% if @user == current_user %>
        <%= link_to "新規動画の投稿", new_video_path, class: "btn btn-success" %>
        <%= link_to "ユーザー編集ページへ", edit_user_path(@user), class: "btn btn-primary" %>
      <% end %>
    </div>

    <div class="recently-video row">
      <h4>最近投稿した動画</h4>
      <div class="show-btn">
        <%= link_to "一覧へ", users_videos_path, class: "btn btn-secondary" %>
      </div>
    </div>

    <div class="recently-videos row">
      <% @videos.each do |video| %>
      <div class="col-lg-3">
        <%= link_to video_path(video) do %>
        <div class="video">
          <video src="<%= rails_blob_path(video.video) %>"　width="640" height="360" type="video/mp4" allowfullscreen></video>
        </div>
        <div class="link-box">
          <span><%= video.title %></span>
          <span><%= video.user.name %></span>
          <span><%= video.created_at.to_s(:datetime_jp) %></span>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>

    <div class="favorite-video row">
      <h4>お気に入り動画</h4>
      <div class="show-btn">
        <%= link_to "一覧へ", users_favorites_path, class: "btn btn-secondary" %>
      </div>
    </div>

    <div class="favorite-videos row">
      <% @favo_videos.each do |video| %>
      <div class="col-lg-3">
        <%= link_to video_path(video) do %>
        <div class="video">
          <video src="<%= rails_blob_path(video.video) %>"　width="640" height="360" type="video/mp4" allowfullscreen></video>
        </div>
        <div class="link-box">
          <span><%= video.title %></span>
          <span><%= video.user.name %></span>
          <span><%= video.created_at.to_s(:datetime_jp) %></span>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>

  <% end %>

</div>

app/views/users/videos.html.erb
<div id="videos">
  <%= render partial: 'users/user_details', locals: { user: @current_user }  %>

  <div class="container">
    <div class="row">

      <div class="col-lg-12">
        <h2>ユーザー投稿動画一覧</h2>
        <div class="jscroll">
          <% @user_videos.each do |video| %>
          <div class="my-video container">
            <div class="row">
              <div class="col-lg-5 col-md-5 col-sm-10 col-xs-10">
                <%= link_to video_path(video) do %>
                <div class="video">
                  <video src="<%= rails_blob_path(video.video) %>"　width="640" height="360" type="video/mp4" allowfullscreen></video>
                </div>
                <% end %>
              </div>
              <div class="col-lg-5 col-md-5 col-sm-10 col-sx-10">
                <%= render partial: "users/attachment", locals: { user: video.user} %> <br>
                <%= video.introduction %>
              </div>
            </div>
            <div class="title-index row">
              <%= link_to video.title %>
            </div>
            <div class="video-status row">
              <span id="like_<%= video.id %>"><%= render partial: 'videos/likes', locals: { video: video} %></span>
              <% unless video.user.id == current_user.id %>
                <span id="favorite_<%= video.id %>"><%= render partial: 'videos/favorites', locals: { video: video} %></span>
              <% end %>
              <%= video.created_at.to_s(:datetime_jp) %>
            </div>
          </div>
          <% end %>
          <%= paginate @user_videos %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/withdraw.html.erb
<div id="withdraw">
  <div class="withdraw-message">
    <p>
      <span>※　注意！！　※</span> <br>
      削除すると今まで投稿した全ての動画、コメント、お気に入りや<br>
      全てのアカウント情報も削除されます。<br>
      本当に削除しますか？
    </p>
  </div>
  <div class="link-box">
    <%= link_to "戻る", edit_user_path(@user), class: "btn btn-info" %>
    <%= link_to "削除", user_path(@user), method: :delete, class: "btn btn-danger delete" %>
  </div>
</div>