config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  root to: "variouses#top"

  # アバウトページ
  get "variouses/about"       => "variouses#about"

  # ユーザーアクション
  get "users/:id/videos"      => "users#videos", as: "users_videos"
  get "users/withdraw"        => "users#withdraw"
  get "users/:id/favorites" => "users#favorites", as: "users_favorites"

  # 検索機能
  get "search" => "videos#search"

  # 新規会員登録の時のルーティングエラーを修正
  get '/users', to: redirect("/users/sign_up")

  resources :users,           only: [:show, :edit, :update, :destroy] do
    resource :relationships,  only: [:create, :destroy]
    get :follows,   on: :member
    get :followers, on: :member
    # memberはidを取得できるようにする
  end

  # 動画アクション
  resources :videos do
    resource  :likes,      only: [:create, :destroy]
    resource  :favorites,  only: [:create, :destroy]
    resources :comments,   only: [:create, :destroy]
  end

  # ルーム機能
  resources :rooms do
    resources   :room_messages, only: [:create, :destroy]
    resources   :room_videos,   only: [:create, :destroy]
    resource    :room_user,     only: [:create, :destroy]
  end

  resources :notifications, only: :index
end

app/models/video.rb
class Video < ApplicationRecord

  require 'miyabi'

  # ActiveStorage
  has_one_attached :video
  validate :video_type

  validates :video,           presence: true
  validates :title,           presence: true
  validates :introduction,    presence: true

  has_many :favorites,        dependent: :destroy
  has_many :comments,         dependent: :destroy
  has_many :likes,            dependent: :destroy

  has_many :notifications,    dependent: :destroy

  belongs_to :user

  # すでにお気に入りされているかどうか調べるメソッド
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # すでにいいねされているかどうか調べるメソッド
  def liked_by?(user)
    self.likes.exists?(user_id: user.id)
  end

  # ActiveStorage画像リサイズメソッド
  def thumbnail
    profile_image.variant(resize: '100x100').processed
  end

  def video_type
    if video.attached? && !video.content_type.in?(%("video/mp4"))
      errors.add(:video, 'の拡張子はmp4で選択してください')
    elsif !video.attached?
      errors.add(:video, "ファイルを添付してください")
    end
  end

  # いいねした時に通知がされるメソッド
  def create_notification_like!(current_user)
    # すでにいいねされているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and video_id = ? and action = ?", current_user.id, user_id, id, 'like'])
    # いいねされてない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        video_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は通知済とする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # コメントが投稿された時に通知がされるメソッド
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人を全て取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(video_id: id).where.not(user_id: current_user.id).distinct
    # selectメソッド...取得したい列を指定するメソッド(今回は:user_id)
    # distinctメソッド...重複レコードを１つにまとめるためのメソッド
    # まず、投稿にコメントしているユーザーのIDリストを取得、自分のコメントは除外、重複した場合は削除する。
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # 投稿者にも通知を送る
    save_notification_comment!(current_user, comment_id, user_id)
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回投稿することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      video_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は通知済とする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  # フォローされた時に通知がされるメソッド
  def create_notification_follow!(current_user)
    # 同じ通知レコードが存在しない時だけ、レコードを作成
    temp = Notification.where(["visitor_id = ? and Visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # 検索機能
  def self.search(search)
    return Video.all unless search
    Video.where(['conversion_title LIKE?', "%#{search}%"])
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  require 'miyabi'

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    @video.user_id = current_user.id
    if @video.title.match(/[一-龠々]/)
      @video.conversion_title = @video.title.to_kanhira.to_roman
    elsif @video.title.is_hira? || @video.title.is_kana?
      @video.conversion_title = @video.title.to_roman
    else
      @video.conversion_title = @video.title
    end
    if @video.save
      redirect_to video_path(@video)
    else
      render :new
    end
  end

  def show
    @video      = Video.find(params[:id])
    @user       = current_user
    @comment    = Comment.new
    @comments   = @video.comments.order(id: "DESC").page(params[:page]).per(8).includes(:user)
  end

  def index
    @videos = Video.order(id: "DESC").page(params[:page]).per(12).includes(:user)
    @user = current_user
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      redirect_to @video
    elsif
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    redirect_to user_path(current_user)
  end

  def search
    word = params[:search]
    unless word.blank?
      if word.match(/[一-龠々]/)
        conversion_word = word.to_kanhira.to_roman
      elsif word.is_hira? || word.is_kana?
        conversion_word = word.to_roman
      else
        conversion_word = word
      end

    end
    @search_video = Video.search(conversion_word).order(id: "DESC").page(params[:page]).per(12).includes(:user)
  end

  private

  # 動画投稿ユーザー以外はURL直打ちで編集に遷移できないようにする
  def ensure_correct_user
    video = Video.find(params[:id])
    unless video.user == current_user
      redirect_back(fallback_location: videos_path)
    end
  end

  def video_params
    params.require(:video).permit(:title, :introduction, :video)
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_comments.html.erb
<% comments.each do |comment| %>
  <% if comment.user.release_status == 1 %>
    <div id="comment-<%= comment.id %>" class="post-comments row">
      <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
        <%= link_to user_path(comment.user) do %>
          <%= render partial: "users/attachment", locals: { user: comment.user} %>
        <% end %>
      </div>
      <div class="col-lg-10 col-md-10 col-sm-9 col-xs-8">
        <%= comment.comment %> <br>
        <%= comment.user.name %>
        <%= comment.created_at.to_s(:datetime_jp) %>
        <% if comment.user == current_user %>
        <%= link_to "コメントを削除", video_comment_path(comment.video, comment), method: :delete, remote: true %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>
<%= paginate comments %>

app/views/videos/_comments_form.html.erb
<%= form_with model: [video, comment], remote: true do |f| %>

<% if comment.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= f.text_area :comment, rows: 3, id: "textarea" %>
<%= f.submit "コメントする", class: "btn btn-primary" %>
<% end %>

app/views/videos/_favorited.html.erb
<div id="fa-icon">
<% if video.favorited_by?(current_user) %>
  <%= link_to video_favorites_path(video.id), method: :delete, remote: true do %>
    <p><%= icon('fas', 'file-video') %> お気に入りから削除</p>
  <% end %>
<% else %>
  <%= link_to video_favorites_path(video.id), method: :post, remote: true do %>
    <p><%= icon('far', 'file-video') %> お気に入りに保存する</p>
  <% end %>
<% end %>
</div>

app/views/videos/_favorites.html.erb
<div id="fa-icon">
<% if video.favorited_by?(current_user) %>
  <p><%= icon('fas', 'file-video') %> お気に入り！</p>
<% else %>
  <%= link_to video_favorites_path(video.id), method: :post, remote: true do %>
    <p><%= icon('far', 'file-video') %> お気に入りに保存する</p>
  <% end %>
<% end %>
</div>

app/views/videos/_likes.html.erb
<div id="fa-icon">
<% if video.liked_by?(current_user) %>
  <%= link_to video_likes_path(video.id), method: :delete, remote: true do %>
    <div id="hearts" class="on HeartAnimation"></div>
  <% end %>
  <div class="like-count"><%= video.likes.count %></div>
<% else %>
  <%= link_to video_likes_path(video.id), method: :post, remote: true do %>
    <div id="heart"></div>
  <% end %>
  <div class="like-count"><%= video.likes.count %></div>
<% end %>
</div>

<script>
  window.onpageshow = function() {
    if(event.persisted){
      window.location.reload();
    }
  };
</script>

app/views/videos/_user_favorite_videos.html.erb
<% favorites.each do |video| %>
  <% if video.user.release_status == 1 %>
    <div class="my-video container">
      <div class="row">
        <div class="col-lg-5 col-md-5 col-sm-10 col-xs-10">
          <%= link_to video_path(video) do %>
          <div class="video">
            <video src="<%= rails_blob_path(video.video) %>"　width="640" height="360" type="video/mp4" allowfullscreen></video>
          </div>
          <% end %>
        </div>
        <div class="user-image　col-lg-5 col-md-5 col-sm-10 col-sx-10">
          <%= render partial: "users/attachment", locals: { user: video.user} %> <br>
          <%= video.introduction %>
        </div>
      </div>
      <div class="title-index row">
        <%= link_to video.title, video_path(video) %>
      </div>
      <div class="video-status row">
        <span id="like_<%= video.id %>"><%= render partial: 'videos/likes', locals: { video: video} %></span>
        <span><%= render partial: 'videos/favorited', locals: { video: video} %></span>
        <%= video.created_at.to_s(:datetime_jp) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/videos/edit.html.erb
<div id="video_edit">
  <div class="container">

    <div class="row">
      <h2>動画の編集画面</h2>
    </div>

    <div class="upload row">
      <%= form_with model: @video, local: true do |f| %>

      <table class="table table-borderless col-lg-10 col-md-10 col-sm-11">
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="video">
            <video src="<%= rails_blob_path(@video.video) %>" type="video/mp4" controls></video>
          </div>
        </div>
        <tbody>
          <tr>
            <td>タイトル</td>
            <td><%= f.text_field :title %></td>
          <tr>
            <td>動画の説明</td>
            <td><%= f.text_area :introduction %></td>
          </tr>
        </tbody>
      </table>
      <div class="link-box">
        <%= f.submit "保存", class: "btn btn-success" %>
        <%= link_to "キャンセル", videos_path, class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<div id="index">
  <%= render partial: 'users/user_details', locals: { user: @user }  %>

<div class="container">
  <div class="row">

    <div class="col-xl-12">
      <div class="row">
        <h2>動画一覧</h2>
      </div>
      <div class="jscroll">
        <div class="row">
          <% @videos.each do |video| %>
            <% if video.user.release_status == 1 %>
              <div class="video-box col-xl-3 col-md-3 col-xs-4 col-xs-5">
                <%= link_to video_path(video) do %>
                <div class="video">
                  <video src="<%= rails_blob_path(video.video) %>"　width="640" height="360" type="video/mp4" allowfullscreen></video>
                </div>
                <div class="row">
                  <div class="video-image col-lx-3 col-md-3 col-sm-12 col-xs-12">
                    <%= render partial: "users/attachment", locals: { user: video.user} %>
                  </div>
                  <div class="video-data col-lx-9 col-md-9 col-sm-12 col-xs-12">
                    <strong><%= video.title %></strong> <br>
                    <%= video.user.name %>
                    <%= video.created_at.to_s(:datetime_jp) %>
                    <!-- いいねとかが入ります -->
                  </div>
                </div>
                <% end %>
                <div id="like_<%= video.id %>" class="likes">
                  <%= render partial: 'videos/likes', locals: { video: video} %>
                </div>
              </div>
            <% end %>
          <% end %>
          <%= paginate @videos %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/videos/new.html.erb
<div id="new">
  <div class="container">

    <div class="row">
      <h2>動画のアップロード</h2>
    </div>

    <div class="upload row">
      <%= form_with model: @video, local: true do |f| %>
      <table class="table table-borderless col-lg-10 col-md-10 col-sm-11">
        <tbody>
          <%= render 'layouts/error_messages', model: f.object %>
          <%= f.file_field :video, class: "file_field" %> <br>
          <tr>
            <td>タイトル</td>
            <td><%= f.text_field :title %></td>
          <tr>
            <td>動画の説明</td>
            <td><%= f.text_area :introduction %></td>
          </tr>
        </tbody>
      </table>
      <p>※ 10秒程度が動画の長さの目安です</p>
      <div class="link-box">
      <%= f.submit "アップロード", class: "btn btn-success" %>
      <%= link_to "キャンセル", videos_path, class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/search.html.erb
<div id="search">
  <div class="user-user_details">
    <%= render partial: 'users/user_details', locals: { user: current_user }  %>
  </div>

  <div class="container">
    <h2>検索結果</h2>

      <% unless @search_video.blank? %>
        <div class="jscroll">
          <div class="row">
          <% @search_video.each do |video| %>
            <% if video.user.release_status == 1 %>
            <div class="video-box col-xl-3 col-md-3 col-xs-4 col-xs-5">
              <%= link_to video_path(video) do %>
              <div class="video">
                <video src="<%= rails_blob_path(video.video) %>"　width="640" height="360" type="video/mp4" allowfullscreen></video>
              </div>
              <div class="data row">
                <div class="video-image col-lx-3 col-md-3 col-sm-12 col-xs-12">
                  <%= render partial: "users/attachment", locals: { user: video.user} %>
                </div>
                <div class="video-data col-lx-9 col-md-9 col-sm-12 col-xs-12">
                  <strong><%= video.title %></strong> <br>
                  <%= video.user.name %>
                  <%= video.created_at.to_s(:datetime_jp) %>
                </div>
              </div>
              <% end %>
            </div>
            <% end %>
          <% end %>
          <%= paginate @search_video %>
          </div>
        </div>
      <% else %>
        <p>検索結果はありません</p>
      <% end %>
  </div>
</div>

app/views/videos/show.html.erb
<div id="show">
  <%= render partial: 'users/user_details', locals: { user: @user }  %>

  <div class="container">
    <div class="row">

      <div class="col-xl-11 col-md-11 col-sm-11 col-xs-11">
        <% if @video.video.attached? %>

        <div class="row">
          <div class="video">
            <video src="<%= rails_blob_path(@video.video) %>" type="video/mp4" controls></video>
          </div>
        </div>

        <div class="title-box row">
          <div class="title">
            <%= @video.title %>
          </div>
        </div>

        <div class="introduction row">
          <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
            <%= @video.introduction %>
          </div>
          <div class="col-lg-3 colmd-3 col-sm-3 col-xs-3">
            <%= @video.created_at.to_s(:datetime_jp) %>
          </div>
        </div>

        <div class="info-box row">
            <div class="user-image col-lg-2 col-md-2 col-sm-2 col-xs-2">
              <%= link_to user_path(@video.user) do %>
                <%= render partial: "users/attachment", locals: { user: @video.user} %>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
              <p><%= @video.user.name %></p>
              <% end %>
            </div>
        </div>

        <!-- いいねやPV数 -->
        <div id="favorites" class="row">
          <div id="like_<%= @video.id %>" class="likes">
            <%= render partial: 'videos/likes', locals: { video: @video} %>
          </div>
          <% unless @video.user == current_user %>
            <div id="favorite_<%= @video.id %>" class="favo">
              <%= render partial: 'videos/favorites', locals: { video: @video} %>
            </div>
            <div id="follow">
              <%= render partial: 'users/follow', locals: { user: @video.user} %>
            </div>
          <% end %>
        </div>

        <div class="link-box">
          <% if @video.user == current_user %>
          <%= link_to "編集する", edit_video_path(@video), class: "btn btn-success" %>
          <%= link_to "動画の削除", video_path(@video), method: :delete, data: { confirm: "動画を削除してもよろしいですか？"}, class: "btn btn-danger" %>
          <% end %>
        </div>

        <div class="comment">コメント</div>
        <!-- コメント機能 -->
        <div id="error-explanation"></div>
        <div id="form-area" class="comments row">
          <%= render partial: 'videos/comments_form', locals: { video: @video, comment: @comment} %>
        </div>

        <!-- 投稿コメント一覧 -->
        <div id="comments" class="jscroll">
          <%= render partial: 'videos/comments', locals: { comments: @comments} %>
        </div>

        <% end %>
      </div>
    </div>
  </div>
</div>