config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  root to: "variouses#top"

  # アバウトページ
  get "variouses/about"       => "variouses#about"

  # ユーザーアクション
  get "users/:id/videos"      => "users#videos", as: "users_videos"
  get "users/withdraw"        => "users#withdraw"
  get "users/:id/favorites" => "users#favorites", as: "users_favorites"

  # 検索機能
  get "search" => "videos#search"

  # 新規会員登録の時のルーティングエラーを修正
  get '/users', to: redirect("/users/sign_up")

  resources :users,           only: [:show, :edit, :update, :destroy] do
    resource :relationships,  only: [:create, :destroy]
    get :follows,   on: :member
    get :followers, on: :member
    # memberはidを取得できるようにする
  end

  # 動画アクション
  resources :videos do
    resource  :likes,      only: [:create, :destroy]
    resource  :favorites,  only: [:create, :destroy]
    resources :comments,   only: [:create, :destroy]
  end

  # ルーム機能
  resources :rooms do
    resources   :room_messages, only: [:create, :destroy]
    resources   :room_videos,   only: [:create, :destroy]
    resource    :room_user,     only: [:create, :destroy]
  end

  resources :notifications, only: :index
end

app/models/room.rb
class Room < ApplicationRecord
  validates :room_name,         presence: true

  has_many :room_messages,      dependent: :destroy
  has_many :room_videos,        dependent: :destroy
  has_many :room_users,         dependent: :destroy

  has_many :user, through: :room_users
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    @room = Room.new
    @roomusers = RoomUser.new
  end

  def create
    @room = Room.new(room_params)
    @room.owner_id = current_user.id
    if @room.save
      RoomUser.create(room_id: @room.id, user_id: current_user.id)
      redirect_to room_path(@room)
    else
      render :new
    end
  end

  def index
    user = User.find_by(id: current_user.id)
    @rooms = user.room
  end

  def show
    set_room
    @room_menber      = @room.user
    @room_message     = RoomMessage.new
    @room_messages    = @room.room_messages.where(params[:id]).includes(user: :room)
    @room_video       = RoomVideo.new
    @room_videos      = @room.room_videos.where(params[:id]).includes(user: :room)
    mixid_data = @room_messages, @room_videos
    mixid_data.flatten!
    mixid_room_data = mixid_data.sort{|a,b| b.created_at <=> a.created_at}
    @room_data = Kaminari.paginate_array(mixid_room_data).page(params[:page]).per(8)
    # sort{|f,s| f.created_at <=> s.created_at} created_atを新しい順で並べ変える

  end

  def edit
    set_room
    @users = current_user.followings & current_user.followers
  end

  def update
    set_room.update(room_user_params)
    redirect_to room_path(@room)
  end

  def destroy
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:room_name, :room_image)
  end

  def room_user_params
    # :user_idsに常に自分のidが入るようにする
    params[:room][:user_ids].push(current_user.id)
    params.require(:room).permit({ :user_ids => [] })
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room_messages.html.erb
<% room_data.each do |obj| %>
  <% if obj.kind_of?(RoomMessage) %>
    <div class="obj row">
      <div class="message-user col-lg-1 col-md-1 col-sm-2 col-xs-2">
        <%= link_to user_path(obj.user) do %>
          <%= render partial: "users/attachment", locals: { user: obj.user} %> <br>
        <% end %>
      </div>
      <div class="message-content col-lg-7 col-md-7 col-sm-5 col-xs-5">
        <span><%= obj.user.name %></span> <br>
        <p><%= obj.message %></p>
      </div>
      <div class="message-info col-lg-3 col-md-3 col-sm-3 col-xs-3">
        <p>
          <%= obj.created_at.to_s(:datetime_jp) %>
          <% if obj.user == current_user %>
            <%= link_to room_room_message_path(obj.room, obj), method: :delete do %>
              <i class="trash fas fa-trash-alt" style="color: red;"></i>
            <% end %>
        </p>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="obj row">
      <div class="message-user col-lg-1 col-md-1 col-sm-2 col-xs-2">
        <%= link_to user_path(obj.user) do %>
          <%= render partial: "users/attachment", locals: { user: obj.user} %> <br>
        <% end %>
      </div>
      <div class="message-content col-lg-7 col-md-7 col-sm-5 col-xs-5">
        <span><%= obj.user.name %></span> <br>
        <div class="video">
          <video src="<%= rails_blob_path(obj.room_video) %>"　width="640" height="360" type="video/mp4" controls></video>
        </div>
      </div>
      <div class="message-info col-lg-3 col-md-3 col-sm-3 col-xs-3">
        <p>
          <%= obj.created_at.to_s(:datetime_jp) %>
          <% if obj.user == current_user %>
            <%= link_to room_room_message_path(obj.room, obj), method: :delete do %>
              <i class="trash fas fa-trash-alt" style="color: red;"></i>
            <% end %>
        </p>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>
<%= paginate room_data %>

app/views/rooms/_room_post_video.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  <span>動画を送る</span>
</button>

<div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">ムービーアップロード</h5>
      </div>
      <%= form_with model: [room, room_video], local: true do |f| %>
        <div class="modal-body">
          <%= f.file_field :room_video, class: "file_field" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "アップロード", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/edit.html.erb
<div id="room-edit">
  <div class="container">
    <h3>ルームメンバーの追加/除外</h3>
    <p>メンバーは相互にフォローしているユーザーが対象です。</p>
    <%= form_with(model: @room, url: room_path(@room), room_id: @room.id, local: true) do |f| %>
      <% if @users.blank? %>
        <p class="not-user">相互にフォローしているユーザーはいません。</p>
      <% else %>
        <div class="checkbox-list">
          <%= f.collection_check_boxes(:user_ids, @users, :id, :name)%>
        </div>
        <div class="update-btn">
          <%= f.submit class: "btn btn-success" %>
        </div>
      <% end %>
      <span><%= link_to "戻る", room_path(@room), class: "btn btn-primary" %></span>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<div id="room-index">
  <div class="user-details">
    <%= render partial: 'users/user_details', locals: { user: current_user }  %>
  </div>

  <div class="container">
    <h3>参加しているグループルーム</h3>
    <% @rooms.each do |room| %>
    <ul>
      <li><%= link_to room.room_name, room_path(room.id) %>
        <% if room.owner_id == current_user.id %>
          <span>(ルームマスター)</span>
        <% end %>
      </li>
    </ul>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div id="new">
  <div class="container">
  <%= form_with model: @room, local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <%= f.label :"ルーム名" %>
  <%= f.text_field :room_name %>
  <%= f.submit "ルーム作成", class: "btn btn-sm btn-primary" %>
  <% end %>

    <div class="room-introduction">
    <ul>
      <li>メンバーは後からルームの中で追加・削除できます</li>
      <li>メンバーは、ルームを作った人だけ追加できます</li>
      <li>追加するメンバーは相互フォローである必要があります</li>
    </ul>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div id="show">
  <div class="container">
    <h2><%= @room.room_name %></h2>

    <div class="menbers">
      <h5>メンバー</h5>
      <div class="row">
        <% @room_menber.each do |menber| %>
        <div class="menber col-lg-1 col-md-1 col-sx-1 col-sm-1">
          <%= link_to user_path(menber) do %>
          <%= render partial: "users/attachment", locals: { user: menber} %> <br>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

    <div class="add-menber row">
    <% if @room.owner_id == current_user.id %>
    <%= link_to "メンバー編集", edit_room_path(@room) %>
    <% end %>
    </div>

    <div class="row">
      <div class="form_field col-lg-5 col-md-5 col-sm-5">
        <%= form_with model: [@room, @room_message], local: true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <%= f.text_area :message, placeholder: "メッセージ...", id: "textarea" %>
          <%= button_tag :type => "submit", class: "btn btn-primary" do %>
            <i class="fas fa-paper-plane"></i>
          <% end %>
        <% end %>
      </div>
      <div class="col-lg-5 col-md-5 col-sm-5">
        <%= render partial: 'rooms/room_post_video', locals: { room: @room, room_video: @room_video} %>
      </div>
    </div>

    <div id="room-messages" class="jscroll">
      <%= render partial: 'rooms/room_messages', locals: { room_data: @room_data} %>
    </div>
  </div>
</div>