config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ルートページ
  root to: "variouses#top"

  # アバウトページ
  get "variouses/about"       => "variouses#about"

  # ユーザーアクション
  get "users/:id/videos"      => "users#videos", as: "users_videos"
  get "users/withdraw"        => "users#withdraw"
  get "users/:id/favorites" => "users#favorites", as: "users_favorites"

  # 検索機能
  get "search" => "videos#search"

  # 新規会員登録の時のルーティングエラーを修正
  get '/users', to: redirect("/users/sign_up")

  resources :users,           only: [:show, :edit, :update, :destroy] do
    resource :relationships,  only: [:create, :destroy]
    get :follows,   on: :member
    get :followers, on: :member
    # memberはidを取得できるようにする
  end

  # 動画アクション
  resources :videos do
    resource  :likes,      only: [:create, :destroy]
    resource  :favorites,  only: [:create, :destroy]
    resources :comments,   only: [:create, :destroy]
  end

  # ルーム機能
  resources :rooms do
    resources   :room_messages, only: [:create, :destroy]
    resources   :room_videos,   only: [:create, :destroy]
    resource    :room_user,     only: [:create, :destroy]
  end

  resources :notifications, only: :index
end

app/controllers/variouses_controller.rb
class VariousesController < ApplicationController
  layout "top"

  def top
    @video = Video.order(created_at: :desc).first
  end

  def about
    # code
  end
end

app/helpers/variouses_helper.rb
module VariousesHelper
end

app/views/variouses/about.html.erb
<div id="about" class="container">
  <div class="about-title">
    What L/Log??
  </div>

  <div class="about-message-top">
    自分の過去を振り返った時、あの時自分はどう思っていたのか。<br>
    どう考えて選択をしてきたのか。<br>
    たくさんの点と点が繋がって今があります。<br>
    自分の大切な思い出を。あるいは、大切な人や仲間たちとの最高の思い出を。<br>
    ここに残していきませんか。
  </div>

  <div class="about-video">
    <video class="video" src="/videos/Sea-38971.mp4" width="640" height="360" muted controls></video>
  </div>

  <div class="about-message-bottom">
    L/Logとは人生（Life）の記録（Log）の略です。<br>
    今までの経験や体験が今の自分に繋がっていると考え、<br>
    自分がどんな人生を歩んできたのか、そんなアプリケーションがあれば、<br>
    今の自分を未来の自分に繋げていけるのでは無いかと考えました。<br>
    人生をもっと豊かに。もっと夢中に。もっと楽しく。<br>
    そんな思いでこのアプリケーションを作りました。<br>
    <%= link_to "Back", root_path %>
  </div>
</div>

app/views/variouses/top.html.erb
<div id="bg-video">
  <video src="/videos/Sea-38971.mp4" autoplay muted loop ></video>
  <div class="overlay">
  </div>
  <p>L/Log</p>
</div>

<div class="message-wrapper container">

  <div class="message-top">
    <p>
      日常のワンシーンを切り取る。<br>
      毎日を積み重ねていく。<br>
      誰でもない、自分だけの記録を残していく。
    </p>
  </div>

  <div class="video">
    <% if @video %>
      <video src="<%= rails_blob_path(@video.video) %>" type="video/mp4" width="640" height="360" muted controls></video>
    <% elsif %>
      <%= image_tag asset_path('guitar-5531027_640.jpg') %>
    <% end %>
  </div>

  <div class="message-bottom">
    <p>自分だけのストーリーを残していきませんか？</p>
  </div>

  <div class="new-registration">
    <%= link_to "さっそく登録する", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to "about", variouses_about_path %>

</div>